name: jscrambler-cli unit tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: Run jscrambler-cli Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run jscrambler-cli tests
        run: pnpm -C packages/jscrambler-cli test
        env:
          CI: true
