name: Release

on:
  push:
    branches:
      - release/staged

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Access Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@dad2b81e50ce3edeb5f3b7ffbd79f731368bd668
        with:
          application_id: ${{ secrets.CODE_INTEGRITY_ACTIONS_APP_ID }}
          application_private_key: ${{ secrets.CODE_INTEGRITY_ACTIONS_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}

      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          version: 11
          runtime: node@24
          cache: true
          run_install: true

      - name: Create Release Pull Request or Publish to Staged npm
        id: changesets
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1
        with:
          publish-script: pnpm ci:publish
          commit-message: "chore(changeset): bump versions"
          pr-title: "[Changeset] Bump Versions"
          create-github-releases: false
          push-git-tags: false
          github-token: ${{ steps.get_workflow_token.outputs.token }}
