name: Release

on:
  push:
    branches:
      - chore/pnpm

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm -r publish --dry-run --publish-branch=chore/pnpm
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        env:
          WEBHOOK_API_URI: ${{ secrets.WEBHOOK_API_URI }}
        run: "wget -X POST \"${WEBHOOK_API_URI}\" --header 'Content-Type: application/json' --post-data '{\"text\": \"New release of `jscrambler` npm packages: ${GITHUB_REF}\"}'"
