name: Release Code Integrity Github Actions

on:
  push:
    tags:
      - '*'

jobs:
  publish-notification:
    runs-on: ubuntu-latest
    name: Tag Code Integrity Actions
    steps:
      - name: Send a publish notification
        run: "wget -X POST \"${{ secrets.WEBHOOK_API_URI }}\" --header 'Content-Type: application/json' --post-data '{\"text\": \"*${{  github.ref_name }}* was published 🚀\"}'"
