name: Release Code Integrity Github Actions

on:
  push:
    tags:
      - '*'

jobs:
  publish-notification:
    runs-on: ubuntu-latest
    name: Tag Code Integrity Actions
    steps:
      - name: Send a publish notification
        run: "wget -X POST \"${{ secrets.TEST_WEBHOOK }}\" --header 'Content-Type: application/json' --post-data '{\"text\": \"`${{  github.ref_name }} *was published*`\"}'"
